// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkttFxZFOmd20HvLwa-sGvkW2qr_OQ60',
    appId: '1:1017961038119:web:b52ae9d5f7f6020a382902',
    messagingSenderId: '1017961038119',
    projectId: 'fir-cloud-msg-65637',
    authDomain: 'fir-cloud-msg-65637.firebaseapp.com',
    storageBucket: 'fir-cloud-msg-65637.firebasestorage.app',
    measurementId: 'G-EQTLW3HMGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCr-cJWHOn8U_MbfBXxRxhvIGQru5AFKo',
    appId: '1:1017961038119:android:e3f1464716884616382902',
    messagingSenderId: '1017961038119',
    projectId: 'fir-cloud-msg-65637',
    storageBucket: 'fir-cloud-msg-65637.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf5HubgtX2PuiPSJmlKn8X-yeYlDngjL0',
    appId: '1:1017961038119:ios:dec6ee6c913f75fd382902',
    messagingSenderId: '1017961038119',
    projectId: 'fir-cloud-msg-65637',
    storageBucket: 'fir-cloud-msg-65637.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudmsg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf5HubgtX2PuiPSJmlKn8X-yeYlDngjL0',
    appId: '1:1017961038119:ios:dec6ee6c913f75fd382902',
    messagingSenderId: '1017961038119',
    projectId: 'fir-cloud-msg-65637',
    storageBucket: 'fir-cloud-msg-65637.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCloudmsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJkttFxZFOmd20HvLwa-sGvkW2qr_OQ60',
    appId: '1:1017961038119:web:2ee0a5ca944cc239382902',
    messagingSenderId: '1017961038119',
    projectId: 'fir-cloud-msg-65637',
    authDomain: 'fir-cloud-msg-65637.firebaseapp.com',
    storageBucket: 'fir-cloud-msg-65637.firebasestorage.app',
    measurementId: 'G-YPV8SDTV3R',
  );
}
